python algo_sma_signal.py	TCS.NS
python algo_sma_signal.py	TAJGVK.NS
python algo_sma_signal.py	ITC.NS
python algo_sma_signal.py	HDFC.NS
python algo_sma_signal.py	HINDUNILVR.NS
python algo_sma_signal.py	DIVISLAB.NS
python algo_sma_signal.py	BAJAJ-AUTO.NS
python algo_sma_signal.py	PFIZER.NS
python algo_sma_signal.py	MARUTI.NS
python algo_sma_signal.py	NESTLEIND.NS
python algo_sma_signal.py	SOUTHBANK.NS
python algo_sma_signal.py	KTKBANK.NS
python algo_sma_signal.py	HDFCBANK.NS
python algo_sma_signal.py	SJVN.NS
python algo_sma_signal.py	KTKBANK.NS
python algo_sma_signal.py	FEDERALBNK.NS
python algo_sma_signal.py	NHPC.NS
python algo_sma_signal.py	GMDCLTD.NS
python algo_sma_signal.py	ITC.NS
python algo_sma_signal.py	NATIONALUM.NS
python algo_sma_signal.py	TATACONSUM.NS
python algo_sma_signal.py	CASTROLIND.NS
python algo_sma_signal.py	CARERATING.NS
python algo_sma_signal.py	PIDILITIND.NS
python algo_sma_signal.py	ASIANPAINT.NS
python algo_sma_signal.py	BRITANNIA.NS
python algo_sma_signal.py	MANAPPURAM.NS