python algo_sma_signal.py	ITC.NS
python algo_sma_signal.py	SOUTHBANK.NS
python algo_sma_signal.py	KTKBANK.NS
python algo_sma_signal.py	SJVN.NS
python algo_sma_signal.py	FEDERALBNK.NS
python algo_sma_signal.py	NHPC.NS
python algo_sma_signal.py	GMDCLTD.NS
python algo_sma_signal.py	NATIONALUM.NS
python algo_sma_signal.py	CASTROLIND.NS
python algo_sma_signal.py	CARERATING.NS
python algo_sma_signal.py	63MOONS.NS
python algo_sma_signal.py	coalindia.ns
python algo_sma_signal.py   HDFCMFGETF.NS
python algo_sma_signal.py   MOREPENLAB.NS
python algo_sma_signal.py   524520.NS
python algo_sma_signal.py   MARKSANS.NS