python algo_tweet_sentiment.py "#NSE"
python algo_tweet_sentiment.py "#Nifty50"
python algo_tweet_sentiment.py "#SEBI"
python algo_tweet_sentiment.py "#SENSEX"
python algo_tweet_sentiment.py "#RBI"

python algo_tweet_sentiment.py "#BJP"
python algo_tweet_sentiment.py "#INC"
python algo_tweet_sentiment.py "@anand_srini"
python algo_tweet_sentiment.py "@BalakrishnanR"
